# Generated by Django 2.2.14 on 2020-07-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20200714_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='userapp/uploads/%Y/%m/%d/'),
        ),
    ]
