# Generated by Django 2.2.14 on 2020-07-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_userprofile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/uploads/%Y/%m/%d/'),
        ),
    ]
